// http://localhost:81/wepic/
document.writeln("<div id=\"topbar\">");
document.writeln("    	<div id=\"topcenterbar\">");
document.writeln("    		<div id=\"topbar-collect\">");
document.writeln("    			<a href=\"javascript:addToFavorite(\'http://www.wepic.cn/\',\'唯图网_商业拍摄 原创商业图片交易平台\')\" id=\"topcollect\">");
document.writeln("                	<span>收藏唯图</span>			");
document.writeln("        		</a>");
document.writeln("       		</div>");
document.writeln("       	");
document.writeln("        	<div id=\"topbar-toolbar\">");
document.writeln("    			");
document.writeln("                <div id=\"divTopBarUesr\">");
document.writeln("                	<div id=\"topBarUser\" class=\"\">");
document.writeln("                    	<a href=\"javascript:\"><span>"+nickName+"</span><i></i></a>");
document.writeln("                    </div>");
document.writeln("                    ");
document.writeln("                	<div id=\"topBarUserDetailed\" style=\"display: none;\">");
document.writeln("                    	<div id=\"topBarUserOne\">");
document.writeln("                        	<div id=\"topBarUserOneHead\">");
document.writeln("                            	<img id=\"porperties\" src=\"http://localhost:81/wepic/userInfoImg/20131223104957.jpg\">");
document.writeln("                                <div id=\"topBarUserOneHeadChange\">");
document.writeln("                                	<div><a href=\"back/personalCentr/user/accountPic.jsp\">更改头像</a></div>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                            <div id=\"topBarUserOneDetailed\"><div id=\"topBarUserOneDetailedOne\"><a id=\"topBarUserOneComeZom\" href=\"javascript:\">进入空间</a><a id=\"topBarUserOneExit\" href=\"logout.do\">退出登录</a></div><div id=\"topBarUserOneDetailedTwo\"><div id=\"topBarUserInfo\"><span>女</span>&nbsp;&nbsp;|<span>内蒙古自治区 包头市 东河区</span></div><div id=\"topBarUserAccount\"><span>余额：</span>&nbsp;&nbsp;<span is=\"topBarUserAccountYE\">600.00</span><a id=\"topBarUserAccountcz\" href=\"javascript:\">充值</a><a id=\"topBarUserAccounttx\" href=\"javascript:\">提现</a></div><div id=\"topBarUserPart\">职业暂无信息</div></div></div>");
document.writeln("                            ");
document.writeln("                            <div id=\"topBarUserTwo\"><div id=\"topBarUserFollowed\" class=\"topBarUserTwo\"><p class=\"topBarUserTwoPOne\">0</p><p class=\"topBarUserTwoPTwo\">已关注</p></div><div id=\"topBarUserFollower\" class=\"topBarUserTwo\"><p class=\"topBarUserTwoPOne\">0</p><p class=\"topBarUserTwoPTwo\">粉丝</p></div><div id=\"topBarUserGoodDiscuss\" class=\"topBarUserTwo\"><p class=\"topBarUserTwoPOne\">0</p><p class=\"topBarUserTwoPTwo\">好评</p></div><div id=\"topBarUserBadDiscuss\" class=\"topBarUserTwo\"><p class=\"topBarUserTwoPOne\">0</p><p class=\"topBarUserTwoPTwo\">差评</p></div></div>");
document.writeln("                            ");
document.writeln("                            <div id=\"topBarUserThree\">");
document.writeln("                                	<div id=\"topBarUserThreeInOutCome\"><p><span class=\"topBarUserThreeInOutComeAtt\">收入排名</span><span class=\"topBarUserThreeInOutComeNum\">暂无排序</span></p><p><span class=\"topBarUserThreeInOutComeAtt\">支出排名</span><span class=\"topBarUserThreeInOutComeNum\">暂无排序</span></p></div>");
document.writeln("                                    <div id=\"topBarUserThreePersonalManagement\">");
document.writeln("                                    	<input type=\"button\" value=\"个人管理中心\">");
document.writeln("                                    </div>");
document.writeln("                                </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            	<div id=\"divTopBarShopping\">    ");
document.writeln("                    	<div id=\"topBarShopping\" class=\"\">");
document.writeln("                    		<a id=\"topshopping\" href=\"#\">购物车<span>888</span>件<i></i></a>");
document.writeln("                    	</div>");
document.writeln("                        ");
document.writeln("                        <div id=\"topBarShoppingDetailed\" style=\"display: none;\">");
document.writeln("                        	<ul>");
document.writeln("                            <li class=\"\">");
document.writeln("                            	<div class=\"topBarShoppingDetailedHead\">");
document.writeln("                            		<img src=\"/wepic/public/images/pic/topUser.jpg\">");
document.writeln("                           		</div>");
document.writeln("                            ");
document.writeln("                            	<div class=\"topBarShoppingDetailedOpert\">");
document.writeln("                                	<p class=\"topBarShoppingDetailedOpertPOne\">");
document.writeln("                                    	<span>作品标题锦屏1</span>");
document.writeln("                                        <b onclick=\"topBarShoppingDetailedOpertPOneExit(this)\" class=\"topBarShoppingDetailedOpertPOneExit\">×</b>");
document.writeln("                                    </p>");
document.writeln("                                    <p class=\"topBarShoppingDetailedOpertPTwo\">编号：");
document.writeln("                                    	<span>4445454464564</span>");
document.writeln("                                        <span class=\"topBarShoppingDetailedOpertPTwoPice\">21221</span>");
document.writeln("                                    </p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            ");
document.writeln("                            <li class=\"\">");
document.writeln("                            	<div class=\"topBarShoppingDetailedHead\">");
document.writeln("                            		<img src=\"/wepic/public/images/pic/topUser.jpg\">");
document.writeln("                           		</div>");
document.writeln("                            ");
document.writeln("                            	<div class=\"topBarShoppingDetailedOpert\">");
document.writeln("                                	<p class=\"topBarShoppingDetailedOpertPOne\">");
document.writeln("                                    	<span>作品标题锦屏2</span>");
document.writeln("                                        <b onclick=\"topBarShoppingDetailedOpertPOneExit(this)\" class=\"topBarShoppingDetailedOpertPOneExit\">×</b>");
document.writeln("                                    </p>");
document.writeln("                                    <p class=\"topBarShoppingDetailedOpertPTwo\">编号：");
document.writeln("                                    	<span>4445454464564</span>");
document.writeln("                                        <span class=\"topBarShoppingDetailedOpertPTwoPice\">21221</span>");
document.writeln("                                    </p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li class=\"\">");
document.writeln("                            	<div class=\"topBarShoppingDetailedHead\">");
document.writeln("                            		<img src=\"/wepic/public/images/pic/topUser.jpg\">");
document.writeln("                           		</div>");
document.writeln("                            ");
document.writeln("                            	<div class=\"topBarShoppingDetailedOpert\">");
document.writeln("                                	<p class=\"topBarShoppingDetailedOpertPOne\">");
document.writeln("                                    	<span>作品标题锦屏3</span>");
document.writeln("                                        <b onclick=\"topBarShoppingDetailedOpertPOneExit(this)\" class=\"topBarShoppingDetailedOpertPOneExit\">×</b>");
document.writeln("                                    </p>");
document.writeln("                                    <p class=\"topBarShoppingDetailedOpertPTwo\">编号：");
document.writeln("                                    	<span>4445454464564</span>");
document.writeln("                                        <span class=\"topBarShoppingDetailedOpertPTwoPice\">21221</span>");
document.writeln("                                    </p>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <!--<li><img src=\"images/pic1/topUser.jpg\"/></li>");
document.writeln("                            <li><img src=\"images/pic1/topUser.jpg\"/></li>-->");
document.writeln("                            </ul>");
document.writeln("                            ");
document.writeln("                            <div id=\"topBarShoppingDetailedFoot\">");
document.writeln("                            	<input type=\"button\" value=\"查看购物车\">");
document.writeln("                            </div>");
document.writeln("                        </div>     ");
document.writeln("                </div>");
document.writeln("                ");
document.writeln("                <div id=\"divTopBarContainer\"> ");
document.writeln("                	<ul>");
document.writeln("                    	<li class=\"\">");
document.writeln("                        	<div id=\"divTopBarWorks\">");
document.writeln("                            	<div class=\"topBarContainer\" id=\"topBarWorks\">");
document.writeln("                                	<a href=\"javascript:\"><span>我的作品</span></a>");
document.writeln("                                </div>");
document.writeln("                            	");
document.writeln("                                <div class=\"topBarDetailed\" id=\"divTopBarWorksDetailed\">");
document.writeln("                                	<p><a href=\"javascript:\">我的作品库</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">我买到的作品</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">我出售的作品</a></p>                                   ");
document.writeln("                                </div>");
document.writeln("                            </div> ");
document.writeln("                        </li>");
document.writeln("                        ");
document.writeln("                        ");
document.writeln("                        <li class=\"\">");
document.writeln("                        	<div id=\"divTopBarPats\">");
document.writeln("                            	<div class=\"topBarContainer\" id=\"topBarPats\">");
document.writeln("                               <a href=\"/wepic/bid!findAllMyBid.action\"><span>我的约拍</span></a>");
document.writeln("                                </div>");
document.writeln("                            	");
document.writeln("                                <div class=\"topBarDetailed\" id=\"divTopBarPatsDetailed\">");
document.writeln("                                	<p><a href=\"javascript:\">新约拍项目</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">我发布的约拍</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">应约中的约拍</a></p>  ");
document.writeln("                                    <p><a href=\"javascript:\">约拍日程</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">约拍记录</a></p>                                 ");
document.writeln("                                </div>");
document.writeln("                            </div> ");
document.writeln("                        </li>");
document.writeln("                        ");
document.writeln("                        <li class=\"\">");
document.writeln("                        	<div id=\"divTopBarInform\">");
document.writeln("                            	<div class=\"topBarContainer\" id=\"topBarInform\">");
document.writeln("                                	<a href=\"javascript:\"><span>消息中心</span>");
document.writeln("                                    	<i></i>");
document.writeln("                                    </a>");
document.writeln("                                </div>");
document.writeln("                            	");
document.writeln("                                <div class=\"topBarDetailed\" id=\"divTopBarInformDetailed\">");
document.writeln("                                	<p><a href=\"javascript:\">查看粉丝</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">查看评价</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">交易提醒</a></p>  ");
document.writeln("                                    <p><a href=\"javascript:\">日程提醒</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">被邀提醒</a></p> ");
document.writeln("                                    <p><a href=\"javascript:\">有新应约者</a></p>  ");
document.writeln("                                    <p><a href=\"javascript:\">经纪人申请</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">系统通知</a></p>                                ");
document.writeln("                                </div>");
document.writeln("                            </div> ");
document.writeln("                        </li>");
document.writeln("                        ");
document.writeln("                        ");
document.writeln("                        <li class=\"\">");
document.writeln("                        	<div id=\"divTopBarUpload\">");
document.writeln("                            	<div class=\"topBarContainer\" id=\"topBarUpload\">");
document.writeln("                                	<a href=\"javascript:\"><span>上传作品</span></a>");
document.writeln("                                </div>");
document.writeln("                            	");
document.writeln("                                <div class=\"topBarDetailed\" id=\"divTopBarUploadDetailed\">");
document.writeln("                                	<p><a href=\"javascript:\">上传到作品库</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">发布图片</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">发布摄影故事</a></p>  ");
document.writeln("                                    <p><a href=\"javascript:\">发布视频</a></p>                                ");
document.writeln("                                </div>");
document.writeln("                            </div> ");
document.writeln("                        </li>");
document.writeln("                        ");
document.writeln("                        ");
document.writeln("                        <li class=\"\">");
document.writeln("                        	<div id=\"divTopBarPublish\">");
document.writeln("                            	<div class=\"topBarContainer\" id=\"topBarPublish\">");
document.writeln("                                	<a href=\"javascript:\"><span>发布约拍</span></a>");
document.writeln("                                </div>");
document.writeln("                            	");
document.writeln("                                <div class=\"topBarDetailed\" id=\"divTopBarPublishDetailed\">");
document.writeln("                                	<p><a href=\"javascript:\">发布约拍的项目</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">招募摄影师</a></p>");
document.writeln("                                    <p><a href=\"javascript:\">招募模特</a></p>  ");
document.writeln("                                    <p><a href=\"javascript:\">发布征集作品项目</a></p>                                ");
document.writeln("                                </div>");
document.writeln("                            </div> ");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            	<!--<a href=\"#\" id=\"topworks\">我的作品</a>");
document.writeln("            	<a href=\"#\" id=\"toppats\">我的约拍</a>");
document.writeln("           	 	<a href=\"#\" id=\"topinform\">消息中心</a>");
document.writeln("            	<a href=\"#\" id=\"topupload\">上传作品</a>");
document.writeln("            	<a href=\"#\" id=\"toppublish\">发布约拍</a>-->");
document.writeln("        	</div>");
document.writeln("        </div>");
document.writeln("    </div>");